### ISSUE TITLE
Add TulipaEnergyModel.jl

### ISSUE THREAD

**Issue by datejada** [jump-dev/open-energy-modeling-benchmarks#25]
Create a set of MIP case studies in TulipaEnergyModel.jl

**Comment by odow** [comment]
The model from https://github.com/jump-dev/open-energy-modeling-benchmarks/pull/26#issuecomment-2453683882 is difficult to solve. I'll leave it to run and get a full log

**Comment by odow** [comment]
It's been running for 3.5 hours, and it's still at
```
Running HiGHS 1.8.0 (git hash: fcfb53414): Copyright (c) 2024 HiGHS under MIT licence terms
Coefficient ranges:
  Matrix [3e-07, 4e+04]
  Cost   [2e+00, 4e+06]
  Bound  [1e+00, 4e+07]
  RHS    [3e-07, 9e+07]
Presolving model
850993 rows, 1465904 cols, 3875096 nonzeros  0s
765359 rows, 1384318 cols, 3569839 nonzeros  4s

Solving MIP model with:
   765359 rows
   1384318 cols (8 binary, 239 integer, 0 implied int., 1384071 continuous)
   3569839 nonzeros

        Nodes      |    B&B Tree     |            Objective Bounds              |  Dynamic Constraints |       Work      
     Proc. InQueue |  Leaves   Expl. | BestBound       BestSol              Gap |   Cuts   InLp Confl. | LpIters     Time

         0       0         0   0.00%   -inf            inf                  inf        0      0      0         0     5.7s
 S       0       0         0   0.00%   -inf            10114494154.6      Large        0      0      0         0   116.8s
```

**Comment by odow** [comment]
@jajhall here's a model for you to investigate: https://github.com/jump-dev/open-energy-modeling-benchmarks/blob/main/instances/TulipaEnergyModel_1_EU_investment_simple-beb8fc0072ed50c7bf40d264ffb87ba24de4ae6736d55a7c0a78209f2c5883ef.mps.gz

**Comment by datejada** [comment]
@odow Thanks for the quick reply. So,

1. I suppose the writing error is something I don't have set up correctly. Then, it is fine; I will look at it. It is okay as long as you can write the MPS files.
2. I have created a new PR #27 to update the script to run for several timesteps to have small, medium, and large instances. The tests on my PC show that the model has started to be challenging to solve for 2016 timesteps (e.g., hours).
3. Since I haven't fixed my problem in point 1, would you mind running the script to get the new .mps files? The equivalent to the initial one is `timestep = 8760`; maybe we can rename the file or create a new one with the new name when running the latest script (whatever is easier).

Thanks!

**Comment by joaquimg** [comment]
Should we open a new issue to track the challenging case?
I want to close this, as Tulipa was added already.

**Comment by odow** [comment]
Maybe in the HiGHS repo?

Here's where the log I have from 2.5 hours:
```
~/git/hpc-scripts/examples/oem_benchmarks> cat 227/log.out
Running HiGHS 1.8.1 (git hash: 4a7f24ac6): Copyright (c) 2024 HiGHS under MIT licence terms
Number of BV entries in BOUNDS section is 7
Number of LI entries in BOUNDS section is 127
Number of UI entries in BOUNDS section is 117
Coefficient ranges:
  Matrix [3e-07, 4e+04]
  Cost   [2e+00, 4e+06]
  Bound  [1e+00, 4e+07]
  RHS    [3e-07, 9e+07]

Presolve is switched off

Solving MIP model with:
   2429440 rows
   1619451 cols (7 binary, 244 integer, 0 implied int., 1569387 continuous)
   6027950 nonzeros
MIP-Timing:          40 - starting analytic centre calculation

Src: B => Branching; C => Central rounding; F => Feasibility pump; H => Heuristic; L => Sub-MIP;
     P => Empty MIP; R => Randomized rounding; S => Solve LP; T => Evaluate node; U => Unbounded;
     z => Trivial zero; l => Trivial lower; u => Trivial upper; p => Trivial point

        Nodes      |    B&B Tree     |            Objective Bounds              |  Dynamic Constraints |       Work      
Src  Proc. InQueue |  Leaves   Expl. | BestBound       BestSol              Gap |   Cuts   InLp Confl. | LpIters     Time

         0       0         0   0.00%   -inf            inf                  inf        0      0      0         0    40.2s
 S       0       0         0   0.00%   -inf            10114494154.9      Large        0      0      0         0   231.2s
 R       0       0         0   0.00%   10111270045.7   10114031605.14     0.03%        0      0      0    517039   296.5s
         0       0         0   0.00%   10111339120.95  10114031605.14     0.03%     1929      8      0    517798   368.2s
         0       0         0   0.00%   10111670743.41  10114031605.14     0.02%     3918     12      0    518236   435.2s
         0       0         0   0.00%   10111792860.3   10114031605.14     0.02%     4800     16      0    518264   502.7s
         0       0         0   0.00%   10111792891.99  10114031605.14     0.02%     5183     19      0    518278   569.2s
```

**Comment by odow** [comment]
It's pretty much solved. Since the logging stops, I assume there's some sort of cycling/infinite loop happening, so if we fix that then we'll get a niiiice speedup in the benchmarks haha.

**Comment by jajhall** [comment]
> @jajhall here's a model for you to investigate: https://github.com/jump-dev/open-energy-modeling-benchmarks/blob/main/instances/TulipaEnergyModel_1_EU_investment_simple-beb8fc0072ed50c7bf40d264ffb87ba24de4ae6736d55a7c0a78209f2c5883ef.mps.gz

This isn't an MPS file

**Comment by jajhall** [comment]
I'd like the MPS file for this instance. Is it what  https://github.com/jump-dev/open-energy-modeling-benchmarks/blob/main/instances/TulipaEnergyModel_1_EU_investment_simple-beb8fc0072ed50c7bf40d264ffb87ba24de4ae6736d55a7c0a78209f2c5883ef.mps.gz is supposed to be?

> Maybe in the HiGHS repo?
> 
> Here's where the log I have from 2.5 hours:
> 
> ```
> ~/git/hpc-scripts/examples/oem_benchmarks> cat 227/log.out
> Running HiGHS 1.8.1 (git hash: 4a7f24ac6): Copyright (c) 2024 HiGHS under MIT licence terms
> Number of BV entries in BOUNDS section is 7
> Number of LI entries in BOUNDS section is 127
> Number of UI entries in BOUNDS section is 117
> Coefficient ranges:
>   Matrix [3e-07, 4e+04]
>   Cost   [2e+00, 4e+06]
>   Bound  [1e+00, 4e+07]
>   RHS    [3e-07, 9e+07]
> 
> Presolve is switched off
> 
> Solving MIP model with:
>    2429440 rows
>    1619451 cols (7 binary, 244 integer, 0 implied int., 1569387 continuous)
>    6027950 nonzeros
> MIP-Timing:          40 - starting analytic centre calculation
> 
> Src: B => Branching; C => Central rounding; F => Feasibility pump; H => Heuristic; L => Sub-MIP;
>      P => Empty MIP; R => Randomized rounding; S => Solve LP; T => Evaluate node; U => Unbounded;
>      z => Trivial zero; l => Trivial lower; u => Trivial upper; p => Trivial point
> 
>         Nodes      |    B&B Tree     |            Objective Bounds              |  Dynamic Constraints |       Work      
> Src  Proc. InQueue |  Leaves   Expl. | BestBound       BestSol              Gap |   Cuts   InLp Confl. | LpIters     Time
> 
>          0       0         0   0.00%   -inf            inf                  inf        0      0      0         0    40.2s
>  S       0       0         0   0.00%   -inf            10114494154.9      Large        0      0      0         0   231.2s
>  R       0       0         0   0.00%   10111270045.7   10114031605.14     0.03%        0      0      0    517039   296.5s
>          0       0         0   0.00%   10111339120.95  10114031605.14     0.03%     1929      8      0    517798   368.2s
>          0       0         0   0.00%   10111670743.41  10114031605.14     0.02%     3918     12      0    518236   435.2s
>          0       0         0   0.00%   10111792860.3   10114031605.14     0.02%     4800     16      0    518264   502.7s
>          0       0         0   0.00%   10111792891.99  10114031605.14     0.02%     5183     19      0    518278   569.2s
> ```

**Comment by joaquimg** [comment]
@jajhall 
It was renamed to
https://github.com/jump-dev/open-energy-modeling-benchmarks/blob/main/instances/TulipaEnergyModel_1_EU_investment_simple_8760h-beb8fc0072ed50c7bf40d264ffb87ba24de4ae6736d55a7c0a78209f2c5883ef.mps.gz

(note the hash is the same)

**Comment by jajhall** [comment]
I've set it running with some additional logging that I have in a development branch (of v1.8.1) that I'm using. It looks very much to me as if the analytic centre calculation (which runs on a separate thread) is taking forever. Since it's being calculated for the centralised rounding heuristic, and an integer feasible solution has been long-since found otherwise, it's pointless. This happens occasionally, and it's hard to know what to do about it. It's tempting to give it 1% of the time limit (when finite), but that would (technically) make the code non-deterministic. Some limit on the number of IPM iterations would be better.

**Comment by odow** [comment]
Ah so to maintain determinism, the code can't progress until the analytic centre returns?

No suggestions for a rule, but my sense from the other solvers is that determinism >>> performance.

**Comment by jajhall** [comment]
> Ah so to maintain determinism, the code can't progress until the analytic centre returns?

There's a synchronisation point where I've seen the main thread wait for ages - in an example where the AC calculation was 70% of solution time. 

The trouble is that if the time limit was 36s, and it sometimes completed just inside 36s, then the code would run differently relative to situations where it timed-out in 36s. 

> No suggestions for a rule, but my sense from the other solvers is that determinism >>> performance.

I need a function of problem size to give a limit the number of IPM iterations. 

Yes, determinism is crucial for many users - which is limiting some use of BLAS by the new IPM solver

**Comment by odow** [comment]
Closing in favor of the upstream issue.

**Comment by jajhall** [comment]
So, it wasn't the number of IPM iterations that was killing performance, but the number of conjugate residual iterations early in the IPM solution process. Introducing a deterministic limit (affine linear function of the number of rows) on the number of conjugate residual iterations, this problem is solved in 250s

Quite a speed up over "going no-where in 2.5 hours"!

**Comment by jajhall** [comment]
So, I solved the Analytic Centre LP using HiGHS simplex, and it took about 30s, whereas HiGHS IPM takes about 5000s.

Naturally I asked myself why there was such a big difference, when IPM is typically much faster than simplex for an LP when no near-optimal basis is known.

The HiGHS IPM solver performs about 20 IPM iterations, each requiring an average of about 2000 conjugate residual (CR) iterations. That figure of 2000 is rather higher than usual. The cost of each CR iteration is dominated by two system solves using a simplex-like basis matrix - like a single simplex iteration. So IPM needs about 80,000 system solves - probably fewer than simplex would require for a problem with 750,000 constraints.

Why the big difference in time?

This problem is hyper-sparse. On average for each simplex system solved there are 2-3 nonzeros in a solution vector of dimension 750,000, requiring access to a comparable proportion of the factors of the basis matrix - a property that's fully exploited in HiGHS. The IPM system solves have solutions that are fully dense, so a complete pass through the factors of the basis matrix is required.

Although an extreme example, in retrospect this difference was always there to be exploited. I see it leading me to making good choices of when not to compute the analytic centre and, conversely, when to use interior point rather than simplex to solve nodes for which no near-optimal basis is known

**Comment by jajhall** [comment]
So, I solved the Analytic Centre LP using HiGHS simplex, and it took about 30s, whereas HiGHS IPM takes about 5000s. The latter performs about 20 IPM iterations, each requiring an average of about 2000 conjugate residual (CR) iterations. That figure of 2000 is rather higher than usual. Each CR iteration requires two system solves using a simplex-like basis matrix - like a simplex iteration. So IPM needs about 80,000 system solves - probably fewer than simplex would require.

Why the big difference in time?

This problem is hyper-sparse. On average for each simplex system solved there are 2-3 nonzeros in a solution vector of dimension 750,000, requiring access to a comparable proportion of the factors of the basis matrix - a property that's fully exploited in HiGHS. The IPM system solves have solutions that are fully dense, so a complete pass through the factors of the basis matrix is required.

Although an extreme example, in retrospect this difference was always there to be exploited. I see it leading me to making good choices of when not to compute the analytic centre and, conversely, when to use interior point rather than simplex to solve nodes for which no near-optimal basis is known

**Comment by odow** [comment]
Nice! I'm pleased this instance has been useful
